<?php

// die(dirname(__FILE__).'/../../wp-load.php');

require_once dirname(__FILE__).'/../../../wp-load.php';

//require_once '/Users/radu/Development/wordpress/wp-load.php';
    
header("Content-type: application/javascript");
?>
var Fpe = {
    options: {},
    broadcast: [],
    next: [],
    prev: [],
    labels: {
	   'actor_on_camera': 'On-Camera Principal',
	   'stunt_performer': 'Stunt Performer',
	   'pilot': 'Pilot',
	   'speciality_act': 'Speciality Act',
	   'dancer': 'Dancer',
	   'actor_off_camera': 'Off-Camera Principal (Ex. Voiceover)',
	   'singer': 'Singer',
	   'extra': 'Extra Performer',
	   'wildspot': 'Wildspot 13 weeks',
	   'program_a': 'Program Class A',
	   'cable': 'Cable Only',
	   'local_cable': 'Local Cable',
	   'dealer': 'Dealer',
	   'internet': 'Move-over-Internet',
	   'newmedia': 'Move-over-New Media',
	   'internet2': 'Made for Internet',
	   'newmedia2': 'Made for New Media',
	   'spanish': 'Spanish Language Program',
	   'spanish_wildspot': 'Spanish Language Wildspot',
	   'foreign': 'Foreign Use',
	   'theatrical': 'Theatrical use',
	   'demo': 'Demo',
	   '6m': '6 months w/o New York',
	   '6m_ny': '6 months w/ New York',
	   'announcer': 'Announcer',
	   'solo_duo': 'Solo or Duo',
	   'group_3': 'Group 3-5',
	   'group_6': 'Group 6-8',
	   'group_9': 'Group 9 or more',
	   'creative_session': 'Creative Session Calls',
	   'singers_contractors': 'Singers Contractors',
	   'network': 'Regional Network',
	   'program': 'Program commercials - 13 weeks',
	   'regional': 'Regional network with at least one major',
	   'psa': 'PSAs',
	   'radio_dealer': 'Dealer',
	   'radio_foreign': 'Foreign Use - 18 month use',
	   'radio_psa': 'PSAs',
	   'local': 'Local program uses',
	   '1_week_unlimited': '1 week unlimited use',
	   '4_week_unlimited': '4 week unlimited use',
	   '8_week_unlimited': '8 week unlimited use',
	   '13_week_unlimited': '13 week unlimited use',
	   '13_week_26_uses': '26 uses in 13 weeks',
	   '13_week_39_uses': '39 uses in 13 weeks',
	   '13_week_accross': '13 weeks use on across-the-board programs',
	   'category1': 'Category I',
	   'category2': 'Category II',
	   'ivr': 'IVR/Phone Prompts',
	   'storecast': 'Storecast',
	   'on': 'On-Camera Performer',
	   'spokesperson': 'On-Camera Spokesperson',
	   'off': 'Off-Camera, 1st Hour',
	   'retakes': 'Off-Camera, Retakes Entire Script',
	   'on_half': 'On-Camera Performer - Half-Day',
	   'on_3': 'On-Camera Performer - 3 Days',
	   'on_w': 'On-Camera Performer - Weekly',
	   'off_short': 'Off-Camera, 3 mins or less, half hour',
	   'off_retakes': 'Off-Camera, Retakes Entire Script, (One Hour)',
	   'off_retakes2': 'Off-Camera, Retakes Partial Script (30 Minutes)',
	   'madein': 'Made-in/Played-in',
	   '50k': 'Up to 50,000 subscribers',
	   '100k': 'Up to 100,000 subscribers',
	   '150k': 'Up to 150,000 subscribers',
	   '200k': 'Up to 200,000 subscribers',
	   '250k': 'Up to 250,000 subscribers',
	   '500k': 'Up to 500,000 subscribers',
	   '750k': 'Up to 750,000 subscribers',
	   '1000k': 'Up to 1,000,000 subscribers',
    }
};

var spanish_markets = [
    {value: 'Albuquerque NM', code: 'albuquerque--nm'},
    {value: 'Atlanta GA', code: 'atlanta--ga'},
    {value: 'Austin TX', code: 'austin--tx'},
    {value: 'Boston MA', code: 'boston--ma'},
    {value: 'Chicago IL', code: 'chicago--il'},
    {value: 'Dallas-Fort Worth TX', code: 'dallas-fort-worth--tx'},
    {value: 'Denver CO', code: 'denver--co'},
    {value: 'El Centro CA; Yuma AZ; and Mexicali MX (combined)', code: 'el-centro--ca--yuma--az--and-mexicali--mx--combined'},
    {value: 'El Paso TX and Juarez MX (combined)', code: 'el-paso--tx-and-juarez--mx--combined'},
    {value: 'Fresno and Visalia CA (combined)', code: 'fresno-and-visalia--ca--combined'},
    {value: 'Houston TX', code: 'houston--tx'},
    {value: 'Laredo TX and Nueva Laredo MX (combined)', code: 'laredo--tx-and-nueva-laredo--mx--combined'},
    {value: 'Las Vegas NV', code: 'las-vegas--nv'},
    {value: 'Los Angeles CA', code: 'los-angeles--ca'},
    {value: 'McAllen TX; Brownsville TX; and Matamoros MX (combined)', code: 'mcallen--tx--brownsville--tx--and-matamoros--mx--combined'},
    {value: 'Miami FL', code: 'miami--fl'},
    {value: 'New York NY', code: 'new-york--ny'},
    {value: 'Orlando FL', code: 'orlando--fl'},
    {value: 'Philadelphia PA', code: 'philadelphia--pa'},
    {value: 'Phoenix AZ', code: 'phoenix--az'},
    {value: 'Puerto Rico', code: 'puerto-rico'},
    {value: 'Sacramento CA', code: 'sacramento--ca'},
    {value: 'San Antonio TX', code: 'san-antonio--tx'},
    {value: 'San Diego CA and Tijuana MX', code: 'san-diego--ca-and-tijuana--mx'},
    {value: 'San Francisco CA', code: 'san-francisco--ca'},
    {value: 'Tampa FL', code: 'tampa--fl'},
    {value: 'Washington DC', code: 'washington--dc'},
];


var costs = {
    agent_percent: <?php echo get_option('_fpe_agent_fee', 10) ?>,
    wildspot_markets: {
        "atlanta": <?php echo get_option('_fpe_fpe_atlanta', 6) ?>,
        "austin": <?php echo get_option('_fpe_fpe_austin', 2) ?>,
        "baltimore": <?php echo get_option('_fpe_fpe_baltimore', 3) ?>,
        "boston": <?php echo get_option('_fpe_fpe_boston', 6) ?>,
        "charlotte": <?php echo get_option('_fpe_fpe_charlotte', 3) ?>,
        "cincinnati": <?php echo get_option('_fpe_fpe_cincinnati', 2) ?>,
        "cleveland": <?php echo get_option('_fpe_fpe_cleveland', 4) ?>,
        "columbus-oh": <?php echo get_option('_fpe_fpe_columbus-oh', 2) ?>,
        "dallas-fort-worth": <?php echo get_option('_fpe_fpe_dallas-fort-worth', 7) ?>,
        "denver": <?php echo get_option('_fpe_fpe_denver', 4) ?>,
        "detroit": <?php echo get_option('_fpe_fpe_detroit', 5) ?>,
        "grand-rapids-kalamazoo-battle-creek": <?php echo get_option('_fpe_fpe_grand-rapids-kalamazoo-battle-creek', 2) ?>,
        "greenville-spartanburg-asheville-anderson-nc": <?php echo get_option('_fpe_fpe_greenville-spartanburg-asheville-anderson-nc', 2) ?>,
        "hartford-new-haven": <?php echo get_option('_fpe_fpe_hartford-new-haven', 2) ?>,
        "houston": <?php echo get_option('_fpe_fpe_houston', 6) ?>,
        "indianapolis": <?php echo get_option('_fpe_fpe_indianapolis', 3) ?>,
        "kansas-city": <?php echo get_option('_fpe_fpe_kansas-city', 2) ?>,
        "las-vegas": <?php echo get_option('_fpe_fpe_las-vegas', 2) ?>,
        "mexico-mexico-city": <?php echo get_option('_fpe_fpe_mexico-mexico-city', 49) ?>,
        "miami": <?php echo get_option('_fpe_fpe_miami', 4) ?>,
        "milwaukee": <?php echo get_option('_fpe_fpe_milwaukee', 2) ?>,
        "minneapolis---st--paul": <?php echo get_option('_fpe_fpe_minneapolis---st--paul', 4) ?>,
        "montreal": <?php echo get_option('_fpe_fpe_montreal', 5) ?>,
        "nashville": <?php echo get_option('_fpe_fpe_nashville', 2) ?>,
        "norfolk-portsmouth-newport-news": <?php echo get_option('_fpe_fpe_norfolk-portsmouth-newport-news', 2) ?>,
        "oklahoma-city": <?php echo get_option('_fpe_fpe_oklahoma-city', 2) ?>,
        "orlando-daytona-beach": <?php echo get_option('_fpe_fpe_orlando-daytona-beach', 4) ?>,
        "philadelphia": <?php echo get_option('_fpe_fpe_philadelphia', 8) ?>,
        "phoenix": <?php echo get_option('_fpe_fpe_phoenix', 5) ?>,
        "pittsburgh": <?php echo get_option('_fpe_fpe_pittsburgh', 3) ?>,
        "portland--or": <?php echo get_option('_fpe_fpe_portland--or', 3) ?>,
        "puerto-rico": <?php echo get_option('_fpe_fpe_puerto-rico', 3) ?>,
        "raleigh-durham": <?php echo get_option('_fpe_fpe_raleigh-durham', 3) ?>,
        "sacramento-stockton": <?php echo get_option('_fpe_fpe_sacramento-stockton', 3) ?>,
        "salt-lake-city": <?php echo get_option('_fpe_fpe_salt-lake-city', 2) ?>,
        "san-antonio": <?php echo get_option('_fpe_fpe_san-antonio', 2) ?>,
        "san-diego": <?php echo get_option('_fpe_fpe_san-diego', 3) ?>,
        "san-francisco": <?php echo get_option('_fpe_fpe_san-francisco', 7) ?>,
        "seattle-tacoma": <?php echo get_option('_fpe_fpe_seattle-tacoma', 5) ?>,
        "st--louis": <?php echo get_option('_fpe_fpe_st--louis', 3) ?>,
        "tampa-st--petersburg": <?php echo get_option('_fpe_fpe_tampa-st--petersburg', 5) ?>,
        "toronto": <?php echo get_option('_fpe_fpe_toronto', 8) ?>,
        "vancouver-b-c-": <?php echo get_option('_fpe_fpe_vancouver-b-c-', 3) ?>,
        "washington-d-c-": <?php echo get_option('_fpe_fpe_washington-d-c-', 6) ?>,
        "west-palm-beach---ft--pierce": <?php echo get_option('_fpe_fpe_west-palm-beach---ft--pierce', 2) ?>
    },
    spanish_markets_weights: {
        "albuquerque--nm": <?php echo get_option('_fpe_spanish_albuquerque--nm', 3) ?>,
        "atlanta--ga": <?php echo get_option('_fpe_spanish_atlanta--ga', 2) ?>,
        "austin--tx": <?php echo get_option('_fpe_spanish_austin--tx', 2) ?>,
        "boston--ma": <?php echo get_option('_fpe_spanish_boston--ma', 2) ?>,
        "chicago--il": <?php echo get_option('_fpe_spanish_chicago--il', 9) ?>,
        "dallas-fort-worth--tx": <?php echo get_option('_fpe_spanish_dallas-fort-worth--tx', 9) ?>,
        "denver--co": <?php echo get_option('_fpe_spanish_denver--co', 4) ?>,
        "el-centro--ca--yuma--az--and-mexicali--mx--combined": <?php echo get_option('_fpe_spanish_el-centro--ca--yuma--az--and-mexicali--mx--combined', 6) ?>,
        "el-paso--tx-and-juarez--mx--combined": <?php echo get_option('_fpe_spanish_el-paso--tx-and-juarez--mx--combined', 11) ?>,
        "fresno-and-visalia--ca--combined": <?php echo get_option('_fpe_spanish_fresno-and-visalia--ca--combined', 4) ?>,
        "houston--tx": <?php echo get_option('_fpe_spanish_houston--tx', 11) ?>,
        "laredo--tx-and-nueva-laredo--mx--combined": <?php echo get_option('_fpe_spanish_laredo--tx-and-nueva-laredo--mx--combined', 2) ?>,
        "las-vegas--nv": <?php echo get_option('_fpe_spanish_las-vegas--nv', 2) ?>,
        "los-angeles--ca": <?php echo get_option('_fpe_spanish_los-angeles--ca', 39) ?>,
        "mcallen--tx--brownsville--tx--and-matamoros--mx--combined": <?php echo get_option('_fpe_spanish_mcallen--tx--brownsville--tx--and-matamoros--mx--combined', 8) ?>,
        "miami--fl": <?php echo get_option('_fpe_spanish_miami--fl', 17) ?>,
        "new-york--ny": <?php echo get_option('_fpe_spanish_new-york--ny', 32) ?>,
        "orlando--fl": <?php echo get_option('_fpe_spanish_orlando--fl', 3) ?>,
        "philadelphia--pa": <?php echo get_option('_fpe_spanish_philadelphia--pa', 3) ?>,
        "phoenix--az": <?php echo get_option('_fpe_spanish_phoenix--az', 6) ?>,
        "puerto-rico": <?php echo get_option('_fpe_spanish_puerto-rico', 21) ?>,
        "sacramento--ca": <?php echo get_option('_fpe_spanish_sacramento--ca', 3) ?>,
        "san-antonio--tx": <?php echo get_option('_fpe_spanish_san-antonio--tx', 8) ?>,
        "san-diego--ca-and-tijuana--mx": <?php echo get_option('_fpe_spanish_san-diego--ca-and-tijuana--mx', 12) ?>,
        "san-francisco--ca": <?php echo get_option('_fpe_spanish_san-francisco--ca', 7) ?>,
        "tampa--fl": <?php echo get_option('_fpe_spanish_tampa--fl', 3) ?>,
        "washington--dc": <?php echo get_option('_fpe_spanish_washington--dc', 3) ?>,
    },
    fees: {
	   tv: {
		  principal_on: {
			 session: <?php echo get_option('_fpe_principal_actor_on_camera', 671.71) ?>,
			 broadcast: {
				wildspot: {
				    unit_2_25: <?php echo get_option('_fpe_tv_wild_spot_on_camera_2_25', 22.99) ?>,
				    unit_26: <?php echo get_option('_fpe_tv_wild_spot_on_camera_26_60', 8.53) ?>,
				    ny: <?php echo get_option('_fpe_tv_wild_spot_on_camera_ny', 1320.01) ?>,
				    ny_unit: <?php echo get_option('_fpe_tv_wild_spot_on_camera_ny_addl_unit', 8.53) ?>,
				    chi: <?php echo get_option('_fpe_tv_wild_spot_on_camera_chi', 1150.55) ?>,
				    chi_unit: <?php echo get_option('_fpe_tv_wild_spot_on_camera_chi_addl_unit', 8.53) ?>,
				    la: <?php echo get_option('_fpe_tv_wild_spot_on_camera_la', 2191.10) ?>,
				    la_unit: <?php echo get_option('_fpe_tv_wild_spot_on_camera_la_addl_unit', 8.53) ?>,
				    major2: <?php echo get_option('_fpe_tv_wild_spot_on_camera_2_major', 1816.55) ?>,
				    major2_unit: <?php echo get_option('_fpe_tv_wild_spot_on_camera_2_major_addl_unit', 8.53) ?>,
				    major3: <?php echo get_option('_fpe_tv_wild_spot_on_camera_3_major', 2191.10) ?>,
				    major3_nit: <?php echo get_option('_fpe_tv_wild_spot_on_camera_3_major', 8.74) ?>,
				},
				cable: {
				    min: <?php echo get_option('_fpe_tv_national_cable_on_camera_min', 671.7) ?>,
				    tiers: {
					   '50': <?php echo get_option('_fpe_tv_national_cable_on_camera_1_50', 11.96) ?>,
					   '100': <?php echo get_option('_fpe_tv_national_cable_on_camera_51_100', 10.39) ?>,
					   '150': <?php echo get_option('_fpe_tv_national_cable_on_camera_101_150', 8.82) ?>,
					   '200': <?php echo get_option('_fpe_tv_national_cable_on_camera_151_200', 7.25) ?>,
					   '1000': <?php echo get_option('_fpe_tv_national_cable_on_camera_201_1000', 0.85) ?>,
					   '2500': <?php echo get_option('_fpe_tv_national_cable_on_camera_1001_2500', 0.81) ?>,
					   '3000': <?php echo get_option('_fpe_tv_national_cable_on_camera_2501_3000', 0.18) ?>,
				    },
				},
				local_cable: {
				    '50k': <?php echo get_option('_fpe_tv_local_cable_on_camera_up_50k', 29.64) ?>,
				    '100k': <?php echo get_option('_fpe_tv_local_cable_on_camera_up_100k', 59.60) ?>,
				    '150k': <?php echo get_option('_fpe_tv_local_cable_on_camera_up_150k', 89.24) ?>,
				    '200k': <?php echo get_option('_fpe_tv_local_cable_on_camera_up_200k', 119.04) ?>,
				    '250k': <?php echo get_option('_fpe_tv_local_cable_on_camera_up_250k', 148.68) ?>,
				    '500k': <?php echo get_option('_fpe_tv_local_cable_on_camera_up_500k', 297.62) ?>,
				    '750k': <?php echo get_option('_fpe_tv_local_cable_on_camera_up_750k', 446.30) ?>,
				    '1000k': <?php echo get_option('_fpe_tv_local_cable_on_camera_up_1000k', 595.08) ?>,
				},
				program_a: {
				    '1': <?php echo get_option('_fpe_tv_program_a_on_use_1', 671.7) ?>,
				    '2': <?php echo get_option('_fpe_tv_program_a_on_use_2', 157.10) ?>,
				    '3-13': <?php echo get_option('_fpe_tv_program_a_on_use_addl', 124.65) ?>,
				    '13g': <?php echo get_option('_fpe_tv_program_a_on_use_13', 1923.20) ?>,
				    '13g_unit': <?php echo get_option('_fpe_tv_program_a_on_use_13_addl', 117.80) ?>,
				},
				dealer: {
				    A: {
					   '6m': <?php echo get_option('_fpe_tv_dealer_on_a_6m', 2229.30) ?>,
					   '6m_ny': <?php echo get_option('_fpe_tv_dealer_on_a_6m_ny', 2520.70) ?>,
				    },
				    B: {
					   '6m': <?php echo get_option('_fpe_tv_dealer_on_b_6m', 3343.95) ?>,
					   '6m_ny': <?php echo get_option('_fpe_tv_dealer_on_b_6m_ny', 3875.70) ?>,
				    }
				},
				internet: {
				    '4week': <?php echo get_option('_fpe_tv_internet_on_camera_4_week', 839.65) ?>,
				    '8week': <?php echo get_option('_fpe_tv_internet_on_camera_8_week', 1175.50) ?>,
				    '1year': <?php echo get_option('_fpe_tv_internet_on_camera_1_year', 2854.75) ?>,
				},
				newmedia: {
				    '4week': <?php echo get_option('_fpe_tv_newmedia_on_camera_4_week', 839.65) ?>,
				    '8week': <?php echo get_option('_fpe_tv_newmedia_on_camera_8_week', 1175.50) ?>,
				    '1year': <?php echo get_option('_fpe_tv_newmedia_on_camera_1_year', 2854.75) ?>,
				},
				internet2: {
				    '4week': <?php echo get_option('_fpe_tv_internet2_on_camera_4_week', 839.65) ?>,
				    '8week': <?php echo get_option('_fpe_tv_internet2_on_camera_8_week', 1175.50) ?>,
				    '1year': <?php echo get_option('_fpe_tv_internet2_on_camera_1_year', 2854.75) ?>,
				},
				newmedia2: {
				    '4week': <?php echo get_option('_fpe_tv_newmedia2_on_camera_4_week', 839.65) ?>,
				    '8week': <?php echo get_option('_fpe_tv_newmedia2_on_camera_8_week', 1175.50) ?>,
				    '1year': <?php echo get_option('_fpe_tv_newmedia2_on_camera_1_year', 2854.75) ?>,
				},
				spanish: <?php echo get_option('_fpe_tv_spanish_on_camera', 2668.15) ?>,
				spanish_wildspot: {
				    unit_1: <?php echo get_option('_fpe_tv_spanish_wildspot_on_unit_1', 705.25) ?>,
				    unit_2_25: <?php echo get_option('_fpe_tv_spanish_wildspot_on_unit_2_25', 24.14) ?>,
				    unit_26: <?php echo get_option('_fpe_tv_spanish_wildspot_on_unit_26', 8.96) ?>,
				},
				demo: <?php echo get_option('_fpe_tv_broadcast_demo_on', 503.90) ?>,
				theatrical: <?php echo get_option('_fpe_tv_broadcast_theatrical_on', 671.70) ?>,
				made_in_played_in: {
				    'oncam_prod': <?php echo get_option('_fpe_mipi_tv_oncam_prin_prod', 570.00) ?>,
				    'oncam_full': <?php echo get_option('_fpe_mipi_tv_oncam_prin_full', 498.00) ?>,
				},
			 } 
		  },
		  principal_off: {
			 session: <?php echo get_option('_fpe_principal_actor_off_camera', 505.05) ?>,
			 broadcast: {
				wildspot: {
                    unit_2_25: <?php echo get_option('_fpe_tv_wild_spot_off_camera_2_25', 15.73) ?>,
                    unit_26: <?php echo get_option('_fpe_tv_wild_spot_off_camera_26_60', 6.69) ?>,
                    ny: <?php echo get_option('_fpe_tv_wild_spot_off_camera_ny', 932.55) ?>,
                    ny_unit: <?php echo get_option('_fpe_tv_wild_spot_off_camera_ny_addl_unit', 6.69) ?>,
                    chi: <?php echo get_option('_fpe_tv_wild_spot_off_camera_chi', 811.50) ?>,
                    chi_unit: <?php echo get_option('_fpe_tv_wild_spot_off_camera_chi_addl_unit', 6.69) ?>,
                    la: <?php echo get_option('_fpe_tv_wild_spot_off_camera_la', 811.50) ?>,
                    la_unit: <?php echo get_option('_fpe_tv_wild_spot_off_camera_la_addl_unit', 6.69) ?>,
                    major2: <?php echo get_option('_fpe_tv_wild_spot_off_camera_2_major', 1223.10) ?>,
                    major2_unit: <?php echo get_option('_fpe_tv_wild_spot_off_camera_2_major_addl_unit', 6.69) ?>,
                    major3: <?php echo get_option('_fpe_tv_wild_spot_off_camera_3_major', 1556.25) ?>,
                    major3_nit: <?php echo get_option('_fpe_tv_wild_spot_off_camera_3_major', 6.85) ?>,
				},
				cable: {
				    min: <?php echo get_option('_fpe_tv_national_cable_off_camera_min', 505.05) ?>,
				    tiers: {
					   '50': <?php echo get_option('_fpe_tv_national_cable_off_camera_1_50', 7.93) ?>,
					   '100': <?php echo get_option('_fpe_tv_national_cable_off_camera_51_100', 6.92) ?>,
					   '150': <?php echo get_option('_fpe_tv_national_cable_off_camera_101_150', 5.87) ?>,
					   '200': <?php echo get_option('_fpe_tv_national_cable_off_camera_151_200', 4.83) ?>,
					   '1000': <?php echo get_option('_fpe_tv_national_cable_off_camera_201_1000', 0.57) ?>,
					   '2500': <?php echo get_option('_fpe_tv_national_cable_off_camera_1001_2500', 0.55) ?>,
					   '3000': <?php echo get_option('_fpe_tv_national_cable_off_camera_2501_3000', 0.12) ?>,
				    },
				},
				local_cable: {
                    '50k': <?php echo get_option('_fpe_tv_local_cable_off_camera_up_50k', 20.22) ?>,
                    '100k': <?php echo get_option('_fpe_tv_local_cable_off_camera_up_100k', 40.71) ?>,
                    '150k': <?php echo get_option('_fpe_tv_local_cable_off_camera_up_150k', 61.10) ?>,
                    '200k': <?php echo get_option('_fpe_tv_local_cable_off_camera_up_200k', 81.48) ?>,
                    '250k': <?php echo get_option('_fpe_tv_local_cable_off_camera_up_250k', 101.81) ?>,
                    '500k': <?php echo get_option('_fpe_tv_local_cable_off_camera_up_500k', 203.78) ?>,
                    '750k': <?php echo get_option('_fpe_tv_local_cable_off_camera_up_750k', 305.54) ?>,
                    '1000k': <?php echo get_option('_fpe_tv_local_cable_off_camera_up_1000k', 407.46) ?>,
				},
				program_a: {
				    '1': <?php echo get_option('_fpe_tv_program_a_off_use_1', 122.95) ?>,
				    '2': <?php echo get_option('_fpe_tv_program_a_off_use_2', 97.80) ?>,
				    '3-13': <?php echo get_option('_fpe_tv_program_a_off_use_addl', 44.40) ?>,
				    '13g': <?php echo get_option('_fpe_tv_program_a_off_use_13', 1487.95) ?>,
				    '13g_unit': <?php echo get_option('_fpe_tv_program_a_off_use_13_addl', 89.50) ?>,
				},
				dealer: {
				    A: {
					   '6m': <?php echo get_option('_fpe_tv_dealer_off_a_6m', 1610.05) ?>,
					   '6m_ny': <?php echo get_option('_fpe_tv_dealer_off_a_6m_ny', 1755.70) ?>,
				    },
				    B: {
					   '6m': <?php echo get_option('_fpe_tv_dealer_off_b_6m', 2411.35) ?>,
					   '6m_ny': <?php echo get_option('_fpe_tv_dealer_off_b_6m_ny', 2637.30) ?>,
				    }
				},
				internet: {
				    '4week': <?php echo get_option('_fpe_tv_internet_off_camera_4_week', 631.30) ?>,
				    '8week': <?php echo get_option('_fpe_tv_internet_off_camera_8_week', 883.85) ?>,
				    '1year': <?php echo get_option('_fpe_tv_internet_off_camera_1_year', 2146.45) ?>,
				},
				newmedia: {
				    '4week': <?php echo get_option('_fpe_tv_newmedia_off_camera_4_week', 631.30) ?>,
				    '8week': <?php echo get_option('_fpe_tv_newmedia_off_camera_8_week', 883.85) ?>,
				    '1year': <?php echo get_option('_fpe_tv_newmedia_off_camera_1_year', 2146.45) ?>,
				},
				internet2: {
				    '4week': <?php echo get_option('_fpe_tv_internet2_off_camera_4_week', 631.30) ?>,
				    '8week': <?php echo get_option('_fpe_tv_internet2_off_camera_8_week', 883.85) ?>,
				    '1year': <?php echo get_option('_fpe_tv_internet2_off_camera_1_year', 2146.45) ?>,
				},
				newmedia2: {
				    '4week': <?php echo get_option('_fpe_tv_newmedia2_off_camera_4_week', 631.30) ?>,
				    '8week': <?php echo get_option('_fpe_tv_newmedia2_off_camera_8_week', 883.85) ?>,
				    '1year': <?php echo get_option('_fpe_tv_newmedia2_off_camera_1_year', 2146.45) ?>,
				},
				spanish: <?php echo get_option('_fpe_tv_spanish_off_camera', 2006.45) ?>,
				spanish_wildspot: {
				    unit_1: <?php echo get_option('_fpe_tv_spanish_wildspot_off_unit_1', 530.30) ?>,
				    unit_2_25: <?php echo get_option('_fpe_tv_spanish_wildspot_off_unit_2_25', 16.52) ?>,
				    unit_26: <?php echo get_option('_fpe_tv_spanish_wildspot_off_unit_26', 7.03) ?>,
				},
				demo: <?php echo get_option('_fpe_tv_broadcast_demo_off', 503.90) ?>,
				theatrical: <?php echo get_option('_fpe_tv_broadcast_theatrical_off', 505.05) ?>,
				made_in_played_in: {				    
				    'offcam_prod': <?php echo get_option('_fpe_mipi_tv_offcam_prin_prod', 428.00) ?>,
				    'offcam_full': <?php echo get_option('_fpe_mipi_tv_offcam_prin_full', 375.00) ?>,
				},
			 } 
		  },
		  stunt_performer: {session: <?php echo get_option('_fpe_principal_actor_on_camera', 671.7) ?>},
		  pilot: {session: <?php echo get_option('_fpe_pilot', 795.5) ?>},
		  speciality_act: {session: <?php echo get_option('_fpe_principal_actor_on_camera', 671.7) ?>},
		  dancer: {session: <?php echo get_option('_fpe_principal_actor_on_camera', 671.7) ?>},
		  singer: {session: <?php echo get_option('_fpe_principal_actor_off_camera', 505.05) ?>},
		  extra: {session: <?php echo get_option('_fpe_extra_actor', 366,37) ?>},
		  made_in_played_in_extra: {
		      'extra_prod': <?php echo get_option('_fpe_mipi_tv_extra_perf_prod', 315.00) ?>,
		      'extra_full': <?php echo get_option('_fpe_mipi_tv_extra_perf_full', 276.00) ?>,
		  },
	   },
	   radio: {
		  announcer: {
			 session: <?php echo get_option('_fpe_radio_actor', 298.10) ?>,
			 multitracking: <?php echo get_option('_fpe_radio_multitracking', 329.45) ?>,
			 broadcast: {
				wildspot: {
				    "13": {
                        unit_2_25: <?php echo get_option('_fpe_radio_wild_spot_announcer_13week_2_25', 4.39) ?>,
                        unit_26: <?php echo get_option('_fpe_radio_wild_spot_announcer_13week_26_60', 3.30) ?>,
                        ny: <?php echo get_option('_fpe_radio_wild_spot_announcer_13week_ny', 446.35) ?>,
                        ny_unit: <?php echo get_option('_fpe_radio_wild_spot_announcer_13week_ny_addl_unit', 3.30) ?>,
                        chi: <?php echo get_option('_fpe_radio_wild_spot_announcer_13week_chi', 404.85) ?>,
                        chi_unit: <?php echo get_option('_fpe_radio_wild_spot_announcer_13week_chi_addl_unit', 3.30) ?>,
                        la: <?php echo get_option('_fpe_radio_wild_spot_announcer_13week_la', 404.85) ?>,
                        la_unit: <?php echo get_option('_fpe_radio_wild_spot_announcer_13week_la_addl_unit', 3.30) ?>,
                        major2: <?php echo get_option('_fpe_radio_wild_spot_announcer_13week_2_major', 544.40) ?>,
                        major2_unit: <?php echo get_option('_fpe_radio_wild_spot_announcer_13week_2_major_addl_unit', 3.30) ?>,
                        major3: <?php echo get_option('_fpe_radio_wild_spot_announcer_13week_3_major', 687.90) ?>,
                        major3_nit: <?php echo get_option('_fpe_radio_wild_spot_announcer_13week_3_major_addl_unit', 3.30) ?>,
                    },
				    "8": {
                        unit_2_25: <?php echo get_option('_fpe_radio_wild_spot_announcer_8week_2_25', 3.51) ?>,
                        unit_26: <?php echo get_option('_fpe_radio_wild_spot_announcer_8week_26_60', 2.64) ?>,
                        ny: <?php echo get_option('_fpe_radio_wild_spot_announcer_8week_ny', 357.05) ?>,
                        ny_unit: <?php echo get_option('_fpe_radio_wild_spot_announcer_8week_ny_addl_unit', 2.64) ?>,
                        chi: <?php echo get_option('_fpe_radio_wild_spot_announcer_8week_chi', 323.90) ?>,
                        chi_unit: <?php echo get_option('_fpe_radio_wild_spot_announcer_8week_chi_addl_unit', 2.64) ?>,
                        la: <?php echo get_option('_fpe_radio_wild_spot_announcer_8week_la', 323.90) ?>,
                        la_unit: <?php echo get_option('_fpe_radio_wild_spot_announcer_8week_la_addl_unit', 2.64) ?>,
                        major2: <?php echo get_option('_fpe_radio_wild_spot_announcer_8week_2_major', 435.55) ?>,
                        major2_unit: <?php echo get_option('_fpe_radio_wild_spot_announcer_8week_2_major_addl_unit', 2.64) ?>,
                        major3: <?php echo get_option('_fpe_radio_wild_spot_announcer_8week_3_major', 550.30) ?>,
                        major3_nit: <?php echo get_option('_fpe_radio_wild_spot_announcer_8week_3_major_addl_unit', 2.64) ?>,
                    },
				},
				network: {
				    '1_week_unlimited': <?php echo get_option('_fpe_radio_network_announcer_1w_unlimited', 504.45) ?>,
				    '4_week_unlimited': <?php echo get_option('_fpe_radio_network_announcer_4w_unlimited', 818.40) ?>,
				    '8_week_unlimited': <?php echo get_option('_fpe_radio_network_announcer_8w_unlimited', 1303.65) ?>,
				    '13_week_unlimited': <?php echo get_option('_fpe_radio_network_announcer_13w_unlimited', 1617.75) ?>,
				    '13_week_26_uses': <?php echo get_option('_fpe_radio_network_announcer_13w_26u', 808.90) ?>,
				    '13_week_39_uses': <?php echo get_option('_fpe_radio_network_announcer_13w_39u', 1218.20) ?>,
				    '13_week_accross': <?php echo get_option('_fpe_radio_network_announcer_13w_a', 1693.95) ?>,
				},
				radio_dealer: {
				    '26_weeks': <?php echo get_option('_fpe_radio_dealer_announcer_26w', 806.20) ?>,
				    '8_weeks': <?php echo get_option('_fpe_radio_dealer_announcer_8w', 403.05) ?>,
				    '26_weeks_effects': <?php echo get_option('_fpe_radio_dealer_announcer_26w_effects', 255.35) ?>,
				    '8_weeks_effects': <?php echo get_option('_fpe_radio_dealer_announcer_8w_effects', 242.30) ?>,
				},
				internet: {
				    '4week': <?php echo get_option('_fpe_radio_announcer_internet_4_week', 372.65) ?>,
				    '8week': <?php echo get_option('_fpe_radio_announcer_internet_8_week', 447.15) ?>,
				    '1year': <?php echo get_option('_fpe_radio_announcer_internet_1_year', 1192.40) ?>,
				},
				newmedia: {
				    '4week': <?php echo get_option('_fpe_radio_announcer_newmedia_4_week', 372.65) ?>,
				    '8week': <?php echo get_option('_fpe_radio_announcer_newmedia_8_week', 447.15) ?>,
				    '1year': <?php echo get_option('_fpe_radio_announcer_newmedia_1_year', 1192.40) ?>,
				},
				internet2: {
				    '4week': <?php echo get_option('_fpe_radio_announcer_internet2_4_week', 372.65) ?>,
				    '8week': <?php echo get_option('_fpe_radio_announcer_internet2_8_week', 447.15) ?>,
				    '1year': <?php echo get_option('_fpe_radio_announcer_internet2_1_year', 1192.40) ?>,
				},
				newmedia2: {
				    '4week': <?php echo get_option('_fpe_radio_announcer_newmedia2_4_week', 372.65) ?>,
				    '8week': <?php echo get_option('_fpe_radio_announcer_newmedia2_8_week', 447.15) ?>,
				    '1year': <?php echo get_option('_fpe_radio_announcer_newmedia2_1_year', 1192.40) ?>,
				},
				single_market: {
				    '13_week': <?php echo get_option('_fpe_radio_single_announcer_13w', 205.45) ?>,
				    '1_year': <?php echo get_option('_fpe_radio_single_announcer_1y', 616.45) ?>,
				},
				made_in_played_in: {				    
				    'prod': <?php echo get_option('_fpe_mipi_radio_actor_prod', 253.00) ?>,
				    'full': <?php echo get_option('_fpe_mipi_radio_actor_full', 221.00) ?>,
				},
				demo: <?php echo get_option('_fpe_radio_announcer_demo', 205.45) ?>,
				regional: <?php echo get_option('_fpe_radio_announcer_regional', 976.20) ?>,
				program: <?php echo get_option('_fpe_radio_announcer_program', 976.20) ?>,
				local: <?php echo get_option('_fpe_radio_announcer_local', 324.00) ?>,
				radio_foreign: <?php echo get_option('_fpe_radio_announcer_foreign', 591.45) ?>,
				psa: <?php echo get_option('_fpe_radio_announcer_psa', 674.45) ?>,
			 }
		  },
		  solo_duo: {
			 session: <?php echo get_option('_fpe_radio_singer', 298,10) ?>,
			 multitracking: <?php echo get_option('_fpe_radio_multitracking', 329.45) ?>,
			 broadcast: {
				wildspot: {
				    "13": {
					   unit_2_25: <?php echo get_option('_fpe_radio_wild_spot_solo_duo_13week_2_25', 4.39) ?>,
					   unit_26: <?php echo get_option('_fpe_radio_wild_spot_solo_duo_13week_26_60', 3.30) ?>,
					   ny: <?php echo get_option('_fpe_radio_wild_spot_solo_duo_13week_ny', 446.35) ?>,
					   ny_unit: <?php echo get_option('_fpe_radio_wild_spot_solo_duo_13week_ny_addl_unit', 3.30) ?>,
					   chi: <?php echo get_option('_fpe_radio_wild_spot_solo_duo_13week_chi', 404.85) ?>,
					   chi_unit: <?php echo get_option('_fpe_radio_wild_spot_solo_duo_13week_chi_addl_unit', 3.30) ?>,
					   la: <?php echo get_option('_fpe_radio_wild_spot_solo_duo_13week_la', 404.85) ?>,
					   la_unit: <?php echo get_option('_fpe_radio_wild_spot_solo_duo_13week_la_addl_unit', 3.30) ?>,
					   major2: <?php echo get_option('_fpe_radio_wild_spot_solo_duo_13week_2_major', 544.40) ?>,
					   major2_unit: <?php echo get_option('_fpe_radio_wild_spot_solo_duo_13week_2_major_addl_unit', 3.30) ?>,
					   major3: <?php echo get_option('_fpe_radio_wild_spot_solo_duo_13week_3_major', 687.90) ?>,
					   major3_nit: <?php echo get_option('_fpe_radio_wild_spot_solo_duo_13week_3_major_addl_unit', 3.30) ?>,
				    },
				    "8": {
					   unit_2_25: <?php echo get_option('_fpe_radio_wild_spot_solo_duo_8week_2_25', 3.51) ?>,
					   unit_26: <?php echo get_option('_fpe_radio_wild_spot_solo_duo_8week_26_60', 2.64) ?>,
					   ny: <?php echo get_option('_fpe_radio_wild_spot_solo_duo_8week_ny', 357.05) ?>,
					   ny_unit: <?php echo get_option('_fpe_radio_wild_spot_solo_duo_8week_ny_addl_unit', 2.64) ?>,
					   chi: <?php echo get_option('_fpe_radio_wild_spot_solo_duo_8week_chi', 323.90) ?>,
					   chi_unit: <?php echo get_option('_fpe_radio_wild_spot_solo_duo_8week_chi_addl_unit', 2.64) ?>,
					   la: <?php echo get_option('_fpe_radio_wild_spot_solo_duo_8week_la', 323.90) ?>,
					   la_unit: <?php echo get_option('_fpe_radio_wild_spot_solo_duo_8week_la_addl_unit', 2.64) ?>,
					   major2: <?php echo get_option('_fpe_radio_wild_spot_solo_duo_8week_2_major', 435.55) ?>,
					   major2_unit: <?php echo get_option('_fpe_radio_wild_spot_solo_duo_8week_2_major_addl_unit', 2.64) ?>,
					   major3: <?php echo get_option('_fpe_radio_wild_spot_solo_duo_8week_3_major', 550.30) ?>,
					   major3_nit: <?php echo get_option('_fpe_radio_wild_spot_solo_duo_8week_3_major_addl_unit', 2.64) ?>,
				    },
				},
				network: {
				    '1_week_unlimited': <?php echo get_option('_fpe_radio_network_solo_duo_1w_unlimited', 504.45) ?>,
				    '4_week_unlimited': <?php echo get_option('_fpe_radio_network_solo_duo_4w_unlimited', 818.40) ?>,
				    '8_week_unlimited': <?php echo get_option('_fpe_radio_network_solo_duo_8w_unlimited', 1303.65) ?>,
				    '13_week_unlimited': <?php echo get_option('_fpe_radio_network_solo_duo_13w_unlimited', 1617.75) ?>,
				    '13_week_26_uses': <?php echo get_option('_fpe_radio_network_solo_duo_13w_26u', 808.90) ?>,
				    '13_week_39_uses': <?php echo get_option('_fpe_radio_network_solo_duo_13w_39u', 1218.20) ?>,
				    '13_week_accross': <?php echo get_option('_fpe_radio_network_solo_duo_13w_a', 1693.95) ?>,
				},
				radio_dealer: {
				    '26_weeks': <?php echo get_option('_fpe_radio_dealer_solo_duo_26w', 806.20) ?>,
				    '8_weeks': <?php echo get_option('_fpe_radio_dealer_solo_duo_8w', 403.05) ?>,
				},
				internet: {
				    '4week': <?php echo get_option('_fpe_radio_solo_duo_internet_4_week', 372.65) ?>,
				    '8week': <?php echo get_option('_fpe_radio_solo_duo_internet_8_week', 447.15) ?>,
				    '1year': <?php echo get_option('_fpe_radio_solo_duo_internet_1_year', 1192.40) ?>,
				},
				newmedia: {
				    '4week': <?php echo get_option('_fpe_radio_solo_duo_newmedia_4_week', 372.65) ?>,
				    '8week': <?php echo get_option('_fpe_radio_solo_duo_newmedia_8_week', 447.15) ?>,
				    '1year': <?php echo get_option('_fpe_radio_solo_duo_newmedia_1_year', 1192.4) ?>,
				},
				internet2: {
				    '4week': <?php echo get_option('_fpe_radio_solo_duo_internet2_4_week', 372.65) ?>,
				    '8week': <?php echo get_option('_fpe_radio_solo_duo_internet2_8_week', 447.15) ?>,
				    '1year': <?php echo get_option('_fpe_radio_solo_duo_internet2_1_year', 1192.40) ?>,
				},
				newmedia2: {
				    '4week': <?php echo get_option('_fpe_radio_solo_duo_newmedia2_4_week', 372.65) ?>,
				    '8week': <?php echo get_option('_fpe_radio_solo_duo_newmedia2_8_week', 447.15) ?>,
				    '1year': <?php echo get_option('_fpe_radio_solo_duo_newmedia2_1_year', 1192.40) ?>,
				},
				made_in_played_in: {				    
				    'prod': <?php echo get_option('_fpe_mipi_radio_actor_prod', 253.00) ?>,
				    'full': <?php echo get_option('_fpe_mipi_radio_actor_full', 221.00) ?>,
				},
				regional: <?php echo get_option('_fpe_radio_solo_duo_regional', 976.20) ?>,
				program: <?php echo get_option('_fpe_radio_solo_duo_program', 976.20) ?>,
				local: <?php echo get_option('_fpe_radio_solo_duo_local', 324.00) ?>,
				radio_foreign: <?php echo get_option('_fpe_radio_solo_duo_foreign', 591.45) ?>,
				radio_psa: <?php echo get_option('_fpe_radio_solo_duo_psa', 674.45) ?>,
			 }
		  },
		  group_3: {
			 session: <?php echo get_option('_fpe_radio_group_3', 329.45) ?>,
			 multitracking: <?php echo get_option('_fpe_radio_multitracking', 329.45) ?>,
			 broadcast: {
				wildspot: {
				    "13": {
					   unit_2_25: <?php echo get_option('_fpe_radio_wild_spot_group_3_13week_2_25', 2.28) ?>,
					   unit_26: <?php echo get_option('_fpe_radio_wild_spot_group_3_13week_26_60', 1.95) ?>,
					   ny: <?php echo get_option('_fpe_radio_wild_spot_group_3_13week_ny', 242.75) ?>,
					   ny_unit: <?php echo get_option('_fpe_radio_wild_spot_group_3_13week_ny_addl_unit', 1.95) ?>,
					   chi: <?php echo get_option('_fpe_radio_wild_spot_group_3_13week_chi', 242.75) ?>,
					   chi_unit: <?php echo get_option('_fpe_radio_wild_spot_group_3_13week_chi_addl_unit', 1.95) ?>,
					   la: <?php echo get_option('_fpe_radio_wild_spot_group_3_13week_la', 242.75) ?>,
					   la_unit: <?php echo get_option('_fpe_radio_wild_spot_group_3_13week_la_addl_unit', 1.95) ?>,
					   major2: <?php echo get_option('_fpe_radio_wild_spot_group_3_13week_2_major', 289.90) ?>,
					   major2_unit: <?php echo get_option('_fpe_radio_wild_spot_group_3_13week_2_major_addl_unit', 1.95) ?>,
					   major3: <?php echo get_option('_fpe_radio_wild_spot_group_3_13week_3_major', 323.00) ?>,
					   major3_nit: <?php echo get_option('_fpe_radio_wild_spot_group_3_13week_3_major_addl_unit', 1.95) ?>,
				    },
				    "8": {
					   unit_2_25: <?php echo get_option('_fpe_radio_wild_spot_group_3_8week_2_25', 2.17) ?>,
					   unit_26: <?php echo get_option('_fpe_radio_wild_spot_group_3_8week_26_60', 1.85) ?>,
					   ny: <?php echo get_option('_fpe_radio_wild_spot_group_3_8week_ny', 230.60) ?>,
					   ny_unit: <?php echo get_option('_fpe_radio_wild_spot_group_3_8week_ny_addl_unit', 1.85) ?>,
					   chi: <?php echo get_option('_fpe_radio_wild_spot_group_3_8week_chi', 230.60) ?>,
					   chi_unit: <?php echo get_option('_fpe_radio_wild_spot_group_3_8week_chi_addl_unit', 1.85) ?>,
					   la: <?php echo get_option('_fpe_radio_wild_spot_group_3_8week_la', 230.60) ?>,
					   la_unit: <?php echo get_option('_fpe_radio_wild_spot_group_3_8week_la_addl_unit', 1.85) ?>,
					   major2: <?php echo get_option('_fpe_radio_wild_spot_group_3_8week_2_major', 275.40) ?>,
					   major2_unit: <?php echo get_option('_fpe_radio_wild_spot_group_3_8week_2_major_addl_unit', 1.85) ?>,
					   major3: <?php echo get_option('_fpe_radio_wild_spot_group_3_8week_3_major', 306.80) ?>,
					   major3_nit: <?php echo get_option('_fpe_radio_wild_spot_group_3_8week_3_major_addl_unit', 1.85) ?>,
				    },
				},
				network: {
				    '1_week_unlimited': <?php echo get_option('_fpe_radio_network_group_3_1w_unlimited', 378.55) ?>,
				    '4_week_unlimited': <?php echo get_option('_fpe_radio_network_group_3_4w_unlimited', 629.35) ?>,
				    '8_week_unlimited': <?php echo get_option('_fpe_radio_network_group_3_8w_unlimited', 1303.65) ?>,
				    '13_week_unlimited': <?php echo get_option('_fpe_radio_network_group_3_13w_unlimited', 1003.00) ?>,
				    '13_week_26_uses': <?php echo get_option('_fpe_radio_network_group_3_13w_26u', 622.00) ?>,
				    '13_week_39_uses': <?php echo get_option('_fpe_radio_network_group_3_13w_39u', 852.95) ?>,
				    '13_week_accross': <?php echo get_option('_fpe_radio_network_group_3_13w_a', 1302.65) ?>,
				},
				radio_dealer: {
				    '26_weeks': <?php echo get_option('_fpe_radio_dealer_group_3_26w', 416.95) ?>,
				    '8_weeks': <?php echo get_option('_fpe_radio_dealer_group_3_8w', 208.50) ?>,
				},
				internet: {
				    '4week': <?php echo get_option('_fpe_radio_group_3_internet_4_week', 274.50) ?>,
				    '8week': <?php echo get_option('_fpe_radio_group_3_internet_8_week', 329.40) ?>,
				    '1year': <?php echo get_option('_fpe_radio_group_3_internet_1_year', 878.40) ?>,
				},
				newmedia: {
				    '4week': <?php echo get_option('_fpe_radio_group_3_newmedia_4_week', 274.50) ?>,
				    '8week': <?php echo get_option('_fpe_radio_group_3_newmedia_8_week', 329.40) ?>,
				    '1year': <?php echo get_option('_fpe_radio_group_3_newmedia_1_year', 878.40) ?>,
				},
				internet2: {
				    '4week': <?php echo get_option('_fpe_radio_group_3_internet2_4_week', 274.50) ?>,
				    '8week': <?php echo get_option('_fpe_radio_group_3_internet2_8_week', 329.40) ?>,
				    '1year': <?php echo get_option('_fpe_radio_group_3_internet2_1_year', 878.40) ?>,
				},
				newmedia2: {
				    '4week': <?php echo get_option('_fpe_radio_group_3_newmedia2_4_week', 274.50) ?>,
				    '8week': <?php echo get_option('_fpe_radio_group_3_newmedia2_8_week', 329.40) ?>,
				    '1year': <?php echo get_option('_fpe_radio_group_3_newmedia2_1_year', 878.40) ?>,
				},
				made_in_played_in: {				    
				    'prod': <?php echo get_option('_fpe_mipi_radio_actor_prod', 253.00) ?>,
				    'full': <?php echo get_option('_fpe_mipi_radio_actor_full', 221.00) ?>,
				},
				regional: <?php echo get_option('_fpe_radio_group_3_regional', 976.20) ?>,
				program: <?php echo get_option('_fpe_radio_group_3_program', 457.60) ?>,
				local: <?php echo get_option('_fpe_radio_group_3_local', 324.00) ?>,
				radio_foreign: <?php echo get_option('_fpe_radio_group_3_foreign', 343.05) ?>,
				radio_psa: <?php echo get_option('_fpe_radio_group_3_psa', 456.60) ?>,
			 }
		  },
		  group_6: {
			 session: <?php echo get_option('_fpe_radio_group_6', 194.35) ?>,
			 multitracking: <?php echo get_option('_fpe_radio_group_6_multitracking', 291.55) ?>,
			 broadcast: {
				wildspot: {
				    "13": {
					   unit_2_25: <?php echo get_option('_fpe_radio_wild_spot_group_6_13week_2_25', 1.95) ?>,
					   unit_26: <?php echo get_option('_fpe_radio_wild_spot_group_6_13week_26_60', 1.50) ?>,
					   ny: <?php echo get_option('_fpe_radio_wild_spot_group_6_13week_ny', 215.50) ?>,
					   ny_unit: <?php echo get_option('_fpe_radio_wild_spot_group_6_13week_ny_addl_unit', 1.64) ?>,
					   chi: <?php echo get_option('_fpe_radio_wild_spot_group_6_13week_chi', 215.50) ?>,
					   chi_unit: <?php echo get_option('_fpe_radio_wild_spot_group_6_13week_chi_addl_unit', 1.64) ?>,
					   la: <?php echo get_option('_fpe_radio_wild_spot_group_6_13week_la', 215.50) ?>,
					   la_unit: <?php echo get_option('_fpe_radio_wild_spot_group_6_13week_la_addl_unit', 1.64) ?>,
					   major2: <?php echo get_option('_fpe_radio_wild_spot_group_6_13week_2_major', 222.40) ?>,
					   major2_unit: <?php echo get_option('_fpe_radio_wild_spot_group_6_13week_2_major_addl_unit', 1.64) ?>,
					   major3: <?php echo get_option('_fpe_radio_wild_spot_group_6_13week_3_major', 249.90) ?>,
					   major3_nit: <?php echo get_option('_fpe_radio_wild_spot_group_6_13week_3_major_addl_unit', 1.64) ?>,
				    },
				    "8": {
					   unit_2_25: <?php echo get_option('_fpe_radio_wild_spot_group_6_8week_2_25', 1.85) ?>,
					   unit_26: <?php echo get_option('_fpe_radio_wild_spot_group_6_8week_26_60', 1.42) ?>,
					   ny: <?php echo get_option('_fpe_radio_wild_spot_group_6_8week_ny', 204.75) ?>,
					   ny_unit: <?php echo get_option('_fpe_radio_wild_spot_group_6_8week_ny_addl_unit', 1.42) ?>,
					   chi: <?php echo get_option('_fpe_radio_wild_spot_group_6_8week_chi', 204.75) ?>,
					   chi_unit: <?php echo get_option('_fpe_radio_wild_spot_group_6_8week_chi_addl_unit', 1.42) ?>,
					   la: <?php echo get_option('_fpe_radio_wild_spot_group_6_8week_la', 204.75) ?>,
					   la_unit: <?php echo get_option('_fpe_radio_wild_spot_group_6_8week_la_addl_unit', 1.42) ?>,
					   major2: <?php echo get_option('_fpe_radio_wild_spot_group_6_8week_2_major', 211.25) ?>,
					   major2_unit: <?php echo get_option('_fpe_radio_wild_spot_group_6_8week_2_major_addl_unit', 1.42) ?>,
					   major3: <?php echo get_option('_fpe_radio_wild_spot_group_6_8week_3_major', 237.40) ?>,
					   major3_nit: <?php echo get_option('_fpe_radio_wild_spot_group_6_8week_3_major_addl_unit', 1.42) ?>,
				    },
				},
				network: {
				    '1_week_unlimited': <?php echo get_option('_fpe_radio_network_group_6_1w_unlimited', 378.55) ?>,
				    '4_week_unlimited': <?php echo get_option('_fpe_radio_network_group_6_4w_unlimited', 562.75) ?>,
				    '8_week_unlimited': <?php echo get_option('_fpe_radio_network_group_6_8w_unlimited', 896.00) ?>,
				    '13_week_unlimited': <?php echo get_option('_fpe_radio_network_group_6_13w_unlimited', 1112.55) ?>,
				    '13_week_26_uses': <?php echo get_option('_fpe_radio_network_group_6_13w_26u', 556.20) ?>,
				    '13_week_39_uses': <?php echo get_option('_fpe_radio_network_group_6_13w_39u', 761.40) ?>,
				    '13_week_accross': <?php echo get_option('_fpe_radio_network_group_6_13w_a', 1164.95) ?>,
				},
				radio_dealer: {
				    '26_weeks': <?php echo get_option('_fpe_radio_dealer_group_6_26w', 333.65) ?>,
				    '8_weeks': <?php echo get_option('_fpe_radio_dealer_group_6_8w', 166.80) ?>,
				},
				internet: {
				    '4week': <?php echo get_option('_fpe_radio_group_6_internet_4_week', 242.95) ?>,
				    '8week': <?php echo get_option('_fpe_radio_group_6_internet_8_week', 291.55) ?>,
				    '1year': <?php echo get_option('_fpe_radio_group_6_internet_1_year', 777.40) ?>,
				},
				newmedia: {
				    '4week': <?php echo get_option('_fpe_radio_group_6_newmedia_4_week', 242.95) ?>,
				    '8week': <?php echo get_option('_fpe_radio_group_6_newmedia_8_week', 291.55) ?>,
				    '1year': <?php echo get_option('_fpe_radio_group_6_newmedia_1_year', 777.40) ?>,
				},
				internet2: {
				    '4week': <?php echo get_option('_fpe_radio_group_6_internet2_4_week', 242.95) ?>,
				    '8week': <?php echo get_option('_fpe_radio_group_6_internet2_8_week', 291.55) ?>,
				    '1year': <?php echo get_option('_fpe_radio_group_6_internet2_1_year', 777.40) ?>,
				},
				newmedia2: {
				    '4week': <?php echo get_option('_fpe_radio_group_6_newmedia2_4_week', 242.95) ?>,
				    '8week': <?php echo get_option('_fpe_radio_group_6_newmedia2_8_week', 291.55) ?>,
				    '1year': <?php echo get_option('_fpe_radio_group_6_newmedia2_1_year', 777.40) ?>,
				},
				made_in_played_in: {				    
				    'prod': <?php echo get_option('_fpe_mipi_radio_actor_prod', 253.00) ?>,
				    'full': <?php echo get_option('_fpe_mipi_radio_actor_full', 221.00) ?>,
				},
				regional: <?php echo get_option('_fpe_radio_group_6_regional', 878.65) ?>,
				program: <?php echo get_option('_fpe_radio_group_6_program', 457.60) ?>,
				local: <?php echo get_option('_fpe_radio_group_6_local', 324.00) ?>,
				radio_foreign: <?php echo get_option('_fpe_radio_group_6_foreign', 236.60) ?>,
				radio_psa: <?php echo get_option('_fpe_radio_group_6_psa', 365.25) ?>,
			 }
		  },
		  group_9: {
			 session: <?php echo get_option('_fpe_radio_group_9', 172.40) ?>,
			 multitracking: <?php echo get_option('_fpe_radio_group_9_multitracking', 258.55) ?>,
			 broadcast: {
				wildspot: {
				    "13": {
					   unit_2_25: <?php echo get_option('_fpe_radio_wild_spot_group_9_13week_2_25', 1.72) ?>,
					   unit_26: <?php echo get_option('_fpe_radio_wild_spot_group_9_13week_26_60', 1.50) ?>,
					   ny: <?php echo get_option('_fpe_radio_wild_spot_group_9_13week_ny', 191.25) ?>,
					   ny_unit: <?php echo get_option('_fpe_radio_wild_spot_group_9_13week_ny_addl_unit', 1.56) ?>,
					   chi: <?php echo get_option('_fpe_radio_wild_spot_group_9_13week_chi', 191.25) ?>,
					   chi_unit: <?php echo get_option('_fpe_radio_wild_spot_group_9_13week_chi_addl_unit', 1.56) ?>,
					   la: <?php echo get_option('_fpe_radio_wild_spot_group_9_13week_la', 191.25) ?>,
					   la_unit: <?php echo get_option('_fpe_radio_wild_spot_group_9_13week_la_addl_unit', 1.56) ?>,
					   major2: <?php echo get_option('_fpe_radio_wild_spot_group_9_13week_2_major', 197.90) ?>,
					   major2_unit: <?php echo get_option('_fpe_radio_wild_spot_group_9_13week_2_major_addl_unit', 1.56) ?>,
					   major3: <?php echo get_option('_fpe_radio_wild_spot_group_9_13week_3_major', 222.40) ?>,
					   major3_nit: <?php echo get_option('_fpe_radio_wild_spot_group_9_13week_3_major_addl_unit', 1.56) ?>,
				    },
				    "8": {
					   unit_2_25: <?php echo get_option('_fpe_radio_wild_spot_group_9_8week_2_25', 1.64) ?>,
					   unit_26: <?php echo get_option('_fpe_radio_wild_spot_group_9_8week_26_60', 1.42) ?>,
					   ny: <?php echo get_option('_fpe_radio_wild_spot_group_9_8week_ny', 181.70) ?>,
					   ny_unit: <?php echo get_option('_fpe_radio_wild_spot_group_9_8week_ny_addl_unit', 1.48) ?>,
					   chi: <?php echo get_option('_fpe_radio_wild_spot_group_9_8week_chi', 181.70) ?>,
					   chi_unit: <?php echo get_option('_fpe_radio_wild_spot_group_9_8week_chi_addl_unit', 1.48) ?>,
					   la: <?php echo get_option('_fpe_radio_wild_spot_group_9_8week_la', 181.70) ?>,
					   la_unit: <?php echo get_option('_fpe_radio_wild_spot_group_9_8week_la_addl_unit', 1.48) ?>,
					   major2: <?php echo get_option('_fpe_radio_wild_spot_group_9_8week_2_major', 188.00) ?>,
					   major2_unit: <?php echo get_option('_fpe_radio_wild_spot_group_9_8week_2_major_addl_unit', 1.48) ?>,
					   major3: <?php echo get_option('_fpe_radio_wild_spot_group_9_8week_3_major', 211.25) ?>,
					   major3_nit: <?php echo get_option('_fpe_radio_wild_spot_group_9_8week_3_major_addl_unit', 1.48) ?>,
				    },
				},
				network: {
				    '1_week_unlimited': <?php echo get_option('_fpe_radio_network_group_9_1w_unlimited', 378.55) ?>,
				    '4_week_unlimited': <?php echo get_option('_fpe_radio_network_group_9_4w_unlimited', 514.15) ?>,
				    '8_week_unlimited': <?php echo get_option('_fpe_radio_network_group_9_8w_unlimited', 803.05) ?>,
				    '13_week_unlimited': <?php echo get_option('_fpe_radio_network_group_9_13w_unlimited', 1019.25) ?>,
				    '13_week_26_uses': <?php echo get_option('_fpe_radio_network_group_9_13w_26u', 508.25) ?>,
				    '13_week_39_uses': <?php echo get_option('_fpe_radio_network_group_9_13w_39u', 691.70) ?>,
				    '13_week_across': <?php echo get_option('_fpe_radio_network_group_9_13w_a', 1067.25) ?>,
				},
				radio_dealer: {
				    '26_weeks': <?php echo get_option('_fpe_radio_dealer_group_9_26w', 208.55) ?>,
				    '8_weeks': <?php echo get_option('_fpe_radio_dealer_group_9_8w', 104.25) ?>,
				},
				internet: {
				    '4week': <?php echo get_option('_fpe_radio_group_9_internet_4_week', 215.50) ?>,
				    '8week': <?php echo get_option('_fpe_radio_group_9_internet_8_week', 258.60) ?>,
				    '1year': <?php echo get_option('_fpe_radio_group_9_internet_1_year', 689.6) ?>0
				},
				newmedia: {
				    '4week': <?php echo get_option('_fpe_radio_group_9_newmedia_4_week', 215.50) ?>,
				    '8week': <?php echo get_option('_fpe_radio_group_9_newmedia_8_week', 258.60) ?>,
				    '1year': <?php echo get_option('_fpe_radio_group_9_newmedia_1_year', 689.6) ?>0
				},
				internet2: {
				    '4week': <?php echo get_option('_fpe_radio_group_9_internet2_4_week', 215.50) ?>,
				    '8week': <?php echo get_option('_fpe_radio_group_9_internet2_8_week', 258.60) ?>,
				    '1year': <?php echo get_option('_fpe_radio_group_9_internet2_1_year', 689.6) ?>0
				},
				newmedia2: {
				    '4week': <?php echo get_option('_fpe_radio_group_9_newmedia2_4_week', 215.50) ?>,
				    '8week': <?php echo get_option('_fpe_radio_group_9_newmedia2_8_week', 258.60) ?>,
				    '1year': <?php echo get_option('_fpe_radio_group_9_newmedia2_1_year', 689.6) ?>0
				},
				made_in_played_in: {				    
				    'prod': <?php echo get_option('_fpe_mipi_radio_actor_prod', 253.00) ?>,
				    'full': <?php echo get_option('_fpe_mipi_radio_actor_full', 221.00) ?>,
				},
				regional: <?php echo get_option('_fpe_radio_group_9_regional', 790.20) ?>,
				program: <?php echo get_option('_fpe_radio_group_9_program', 457.60) ?>,
				local: <?php echo get_option('_fpe_radio_group_9_local', 324.00) ?>,
				radio_foreign: <?php echo get_option('_fpe_radio_group_9_foreign', 189.20) ?>,
				radio_psa: <?php echo get_option('_fpe_radio_group_9_psa', 228.45) ?>,
			 }
		  },
		  creative_session: {session: <?php echo get_option('_fpe_radio_creative_session', 266.90) ?>},
		  singers_contractors: {session: <?php echo get_option('_fpe_radio_singers_contractors', 102.35) ?>},
	   },
	   industrial: {
		  category1: {
              on: <?php echo get_option('_fpe_psa_category1_on', 519.50) ?>,
              on_half: <?php echo get_option('_fpe_psa_category1_on_half', 337.50) ?>,
              on_3: <?php echo get_option('_fpe_psa_category1_on_3', 1308) ?>,
              on_w: <?php echo get_option('_fpe_psa_category1_on_w', 1826.00) ?>,
              off: <?php echo get_option('_fpe_psa_category1_off', 425.50) ?>,
              off_addl: <?php echo get_option('_fpe_psa_category1_off_addl', 121) ?>,
              off_short: <?php echo get_option('_fpe_psa_category1_off_short', 213) ?>,
              retakes: <?php echo get_option('_fpe_psa_category1_retakes', 425.50) ?>,
              retakes_addl: <?php echo get_option('_fpe_psa_category1_retakes_addl', 124.50) ?>,
              spokesperson: <?php echo get_option('_fpe_psa_category1_spokesperson', 945.00) ?>,
              spokesperson_add: <?php echo get_option('_fpe_psa_category1_spokesperson_add', 519.50) ?>,
		  },
		  category2: {
              on: <?php echo get_option('_fpe_psa_category2_on', 647.00) ?>,
              on_half: <?php echo get_option('_fpe_psa_category2_on_half', 420.50) ?>,
              on_3: <?php echo get_option('_fpe_psa_category2_on_3', 1613) ?>,
              on_w: <?php echo get_option('_fpe_psa_category2_on_w', 2261.50) ?>,
              off: <?php echo get_option('_fpe_psa_category2_off', 474.00) ?>,
              off_addl: <?php echo get_option('_fpe_psa_category2_off_addl', 124.50) ?>,
              off_short: <?php echo get_option('_fpe_psa_category2_off_short', 237) ?>,
              retakes: <?php echo get_option('_fpe_psa_category2_retakes', 474.00) ?>,
              retakes_addl: <?php echo get_option('_fpe_psa_category2_retakes_addl', 124.50) ?>,
              spokesperson: <?php echo get_option('_fpe_psa_category2_spokesperson', 1121.00) ?>,
              spokesperson_add: <?php echo get_option('_fpe_psa_category2_spokesperson_add', 647) ?>,
		  },
		  ivr: {
              first: <?php echo get_option('_fpe_psa_ivr_first', 425.50) ?>,
              half: <?php echo get_option('_fpe_psa_ivr_half', 254.00) ?>,
              over: <?php echo get_option('_fpe_psa_ivr_over', 124.50) ?>,
          },
		  storecast: {
			 '3': <?php echo get_option('_fpe_psa_storecast_3', 425.50) ?>,
			 '6': <?php echo get_option('_fpe_psa_storecast_6', 851.00) ?>,
		  },
	   }
    }
};
